parameters:
    elastica_queue_suffix: '_populate'

old_sound_rabbit_mq:
    producers:
        vadiktok_elastica:
            connection: default
            exchange_options: { name: "%vadiktok_elastica.queue_name%", type: direct }
            queue_options:    { name: "%vadiktok_elastica.queue_name%" }
    consumers:
        vadiktok_elastica:
            connection: default
            exchange_options: { name: "%vadiktok_elastica.queue_name%", type: direct }
            queue_options:    { name: "%vadiktok_elastica.queue_name%" }
            callback: vadiktok.rabbitmq.consumer.elastica

services:
    vadiktok.rabbitmq.consumer.elastica:
        class: Vadiktok\ElasticaBundle\ElasticaConsumer
        arguments:
            - "@fos_elastica.pager_provider_registry"
            - "@fos_elastica.persister_registry"
            - '@event_dispatcher'

    vadiktok.rabbitmq.elastica.queue_pager_perister:
        class: Vadiktok\ElasticaBundle\QueuePagerPersister
        arguments:
            - '@fos_elastica.persister_registry'
            - '@event_dispatcher'
            - '@old_sound_rabbit_mq.vadiktok_elastica_producer'
        tags:
            - { name: 'fos_elastica.pager_persister', persisterName: 'queue' }
