services:
    vadiktok.rabbitmq.consumer.elastica:
        class: Vadiktok\RabbitMQElasticaBundle\ElasticaConsumer
        arguments:
            - "@fos_elastica.pager_provider_registry"
            - "@fos_elastica.persister_registry"
            - '@event_dispatcher'

    vadiktok.rabbitmq.elastica.queue_pager_perister:
        class: Vadiktok\RabbitMQElasticaBundle\QueuePagerPersister
        arguments:
            - '@fos_elastica.persister_registry'
            - '@event_dispatcher'
            - '@old_sound_rabbit_mq.vadiktok_elastica_producer'
        tags:
            - { name: 'fos_elastica.pager_persister', persisterName: 'queue' }
